version: '3.8'

services:
  app:
    build: .
    ports:
      - "2000:2000"
    environment:
      - DB_HOST=postgres
      - NODE_ENV=production
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8473403
      POSTGRES_DB: fut
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 